// packages/theme-react/src/components/ArticleCard.tsx
import * as React from 'react';
import { createStyles, makeStyles, Theme } from '@material-ui/core/styles';
import { Link as RouterLink } from 'react-router-dom';
import Card from '@material-ui/core/Card';
import CardActionArea from '@material-ui/core/CardActionArea';
import CardContent from '@material-ui/core/CardContent';
import CardMedia from '@material-ui/core/CardMedia';
import Typography from '@material-ui/core/Typography';
import { CARD_MAX_WIDTH, COVER_HEIGHT } from '@theme-react/constants';
import { ArticleContext } from '@blog/common/interfaces/articles/article-context';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    card: {
      margin: theme.spacing(1),
      maxWidth: CARD_MAX_WIDTH,
      [theme.breakpoints.down('sm')]: {
        margin: theme.spacing(1, 0, 0, 0)
      }
    },
    media: {
      width: '100%',
      maxWidth: '100%'
    }
  })
);

export const ArticleCard: React.FC<Partial<ArticleContext>> = (props) => {
  const classes = useStyles();

  return (
    <Card className={classes.card}>
      <CardActionArea component={RouterLink} to={String(props['link'])}>
        <CardMedia
          className={classes.media}
          component="img"
          image={props.cover}
          title={props.title}
          alt={props.title}
        />
        <CardContent>
          <Typography gutterBottom variant="h5" component="h2">
            {props.title}
          </Typography>
          <Typography variant="body2" color="textSecondary" component="p">
            {props.summary}
          </Typography>
        </CardContent>
      </CardActionArea>
    </Card>
  );
};

// packages/theme-vue/src/components/ArticleCard.vue
<template>
  <md-card class="article-card">
    <md-card-media class="article-cover">
      <img :src="article.cover" alt="cover" />
    </md-card-media>
    <md-card-header>
      <div class="md-title">{{ article.title }}</div>
      <div class="md-subhead">{{ formatDate(article.created) }}</div>
    </md-card-header>

    <md-card-content>
      {{ article.summary }}
    </md-card-content>

    <md-card-actions>
      <md-button :to="article['link']">More</md-button>
    </md-card-actions>
  </md-card>
</template>

<script lang="ts">
import { Component, PropSync, Vue } from 'vue-property-decorator';
import { ArticleContext } from '@blog/common/interfaces/articles/article-context';
import { format, parseISO } from 'date-fns';

@Component
export default class ArticleCard extends Vue {
  @PropSync('data') article!: Partial<ArticleContext>;

  formatDate(date) {
    return format(parseISO(date), 'yyyy-MM-dd');
  }
}
</script>

<style lang="less" scoped>
.article-card {
  max-width: 800px;
  margin: 8px;

  .article-cover {
    img {
      object-fit: cover;
      max-height: 300px;
      max-width: 800px;
    }
  }
}
</style>
