// packages/theme-vue/src/components/Comment.vue
<template>
  <div class="comment" v-if="options">
    <vue-disqus :shortname="options.shortname" :identifier="options.identifier" :url="options.url"></vue-disqus>
  </div>
</template>

<script lang="ts">
import { Component, PropSync, Vue } from 'vue-property-decorator';

@Component({})
export default class Comment extends Vue {
  @PropSync('data') options!: {
    shortname: string;
    identifier: string;
    url: string;
  };
}
</script>

<style scoped lang="less">
.comment {
}
</style>

// packages/theme-react/src/components/Comment.tsx
import * as React from 'react';

export interface CommentProps {
  title: string;
  disqus?: {
    identifier: string;
    url: string;
    shortname: string;
  };
}

const EMPTY_DISQUS_CONFIG = {
  identifier: '',
  url: '',
  shortname: ''
};

export const Comment = (props) => {
  const disqusConfig = props.disqus || EMPTY_DISQUS_CONFIG;

  return <React.Fragment />;
};
