// packages/theme-vue/src/components/ArticleDetail.vue
<template>
  <md-card class="article-detail" v-if="article">
    <md-card-media class="article-cover">
      <img :src="article.cover" alt="cover" />
    </md-card-media>

    <md-card-content v-html="article.html" class="markdown-body"> </md-card-content>

    <md-card-content>
      <keyword v-for="item in article.tags" :key="item.id" :data="item"></keyword>
    </md-card-content>

    <md-card-content>
      <comment :data="article['disqus']"></comment>
    </md-card-content>
  </md-card>
</template>

<script lang="ts">
import { Component, PropSync, Vue } from 'vue-property-decorator';
import { ArticleContext } from '@blog/common/interfaces/articles/article-context';
import { format, parseISO } from 'date-fns';
import Keyword from '@theme-vue/components/Keyword.vue';
import Comment from '@theme-vue/components/Comment.vue';
import '@theme-vue/markdown.css';

@Component({
  components: {
    Keyword,
    Comment
  }
})
export default class ArticleDetail extends Vue {
  @PropSync('data') article!: Partial<ArticleContext>;

  formatDate(date) {
    return format(parseISO(date), 'yyyy-MM-dd');
  }
}
</script>

<style scoped lang="less">
.article-detail {
  max-width: 800px;
  margin: 8px;

  .article-cover {
  }
}
</style>

// themes/theme-react/src/components/ArticleDetail.tsx
import '@theme-react/markdown.css';
import * as React from 'react';
import { ArticleContext } from '@blog/common/interfaces/articles/article-context';
import { createStyles, makeStyles, Theme } from '@material-ui/core/styles';
import { CARD_MAX_WIDTH } from '@theme-react/constants';
import { Comment } from 'react-disqus-components';
import { KeywordChip } from '@theme-react/components/KeywordChip';
import Typography from '@material-ui/core/Typography';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      margin: theme.spacing(0),
      maxWidth: CARD_MAX_WIDTH,
      width: '100%',
      padding: theme.spacing(0, 2),
      [theme.breakpoints.down('sm')]: {
        padding: theme.spacing(1)
      }
    },
    cover: {
      width: '100%',
      maxWidth: '100%'
    },
    divider: {
      marginTop: theme.spacing(2)
    }
  })
);

export const ArticleDetail: React.FC<Partial<ArticleContext>> = (props) => {
  const classes = useStyles();

  return (
    <div className={classes.root}>
      <img src={props.cover} alt={props.title} className={classes.cover} />
      <Typography
        component="div"
        className="markdown-body"
        dangerouslySetInnerHTML={{
          __html: props.html || ''
        }}
      />

      <div className={classes.divider} />

      {props.tags && (props.tags as any).map((keyword) => <KeywordChip key={keyword.id} {...keyword} />)}
      <Comment title={props.title} {...props['disqus']} />
    </div>
  );
};
